### PR TITLE
make sure SearchDateLen supports Firefox

### PR DESCRIPTION
**Pull request by LaruYan**
Tested both Chrome 72 and Firefox 65.

Displays an error about unspecified manifest entry "browser_specific_settings", But It works on fine.

### CODE REVIEW

**Comment by LaruYan** [comment]
It seems Chrome/Whale store won't reject * about unrecognized manifest entry. get peace of mind. :)

gaeulbyul owns Chrome/Whale/Opera/Firefox extension 'Mirror-of-block' and used "application", which is an old name of "browser_specific_settings".
https://github.com/gaeulbyul/MirrorOfBlock/blob/master/src/manifest.json#L12

* see this thread (Korean)
https://mobile.twitter.com/gaeulbyul/status/1099253867437420545

**Comment by SD810** [comment]
Code looks good.

Would you publish this on Firefox store?

I only use Chrome, don't know about Firefox, Sorry about that.

Thank you for contribution.

**Comment by LaruYan** [comment]
I'll try it later.
 you're welcome 😄

**Comment by LaruYan** [comment]
Submitted Addon for Firefox.
After review by human processed, addon will be shown at: 
https://addons.mozilla.org/firefox/addon/searchdatelen/

**Comment by SD810** [comment]
Looks it is published after review, it's fater than Chrome store.
Thank you.

**Pull request merged**
